version: '3.8'

services:
  mysql:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    volumes:  
      - "${MYSQL_STORE}:/var/lib/mysql"
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # ports:
    #   - "3306:3306"
    networks:
      - web_network
    environment:
      MYSQL_ROOT_PASSWORD: 'rootPassword12#$'
      # MYSQL_USER: 'test'
      # MYSQL_PASS: 'password'

  redis:
    container_name: redisdb
    image: redis:alpine
    command: redis-server /etc/redis/redis.conf 
    restart: always
    volumes:
      - "${REDIS_STORE}:/data"
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
    # ports:
    #   - "6379:6379"
    networks:
      - web_network

  web_server:
    image: web_server:latest
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - web_network
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:80

networks:
  web_network:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.28.0.0/16
    #       gateway: 172.28.0.1
