version: '3.8'

services:
  mysql:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    volumes:  
      - "${MYSQL_STORE}:/var/lib/mysql"
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # ports:
    #   - "3306:3306"
    networks:
      - web_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWD}

  redis:
    container_name: redisdb
    image: redis:alpine
    command: redis-server /etc/redis/redis.conf 
    restart: always
    volumes:
      - "${REDIS_STORE}:/data"
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
    # ports:
    #   - "6379:6379"
    networks:
      - web_network

  web_server:
    container_name: web_server
    image: web_server:latest
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config # allow hot swap config files
    networks:
      - web_network
    depends_on:
      - mysql
      - redis
      - traefik
    labels:
      - "traefik.enable=true"
      # http route for localhost only
      - "traefik.http.routers.web_server.rule=Host(`server.localhost`)"
      - "traefik.http.routers.web_server.entrypoints=web"
      - "traefik.http.routers.web_server.service=web_server"
      - "traefik.http.services.web_server.loadbalancer.server.port=80"
      # https route for domain name 
      - "traefik.http.routers.web_server_secure.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.web_server_secure.entrypoints=websecure"
      - "traefik.http.routers.web_server_secure.service=web_server"
      - "traefik.http.routers.web_server_secure.tls.certresolver=web_resolver"
      - "traefik.http.services.web_server_secure.loadbalancer.server.port=80"
  
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    # ports:
    #   - 16686:16686
    networks:
      - web_network
    volumes:
      - ./jaeger:/badger
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.${LOCAL_DOMAIN_NAME}`)"
      - "traefik.http.routers.jaeger.service=jaeger"
      - "traefik.http.routers.jaeger.entrypoints=web"
      - "traefik.http.routers.jaeger.middlewares=ipfilter"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - 8080:80
      - 8081:443
    networks:
      - web_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/traefik
    command:
      # - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/traefik/logs/access.log"
      - "--api=true"
      - "--api.dashboard=true"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
      - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.web_resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.web_resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.web_resolver.acme.email=${EMAIL_ADDRESS}"
      - "--certificatesresolvers.web_resolver.acme.storage=/traefik/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${LOCAL_DOMAIN_NAME}`)||PathPrefix(`/api`, `/dashboard`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=ipfilter,auth"
      - "traefik.http.middlewares.ipfilter.ipwhitelist.sourcerange=127.0.0.1, ${LAN_SUBNET}"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/traefik/users/usersfile" #admin:password

networks:
  web_network:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.28.0.0/16
    #       gateway: 172.28.0.1
